### PR TITLE
Add Makefile target to build the doc

### PR DESCRIPTION
**Pull request by maximedenes**
##### Motivation for this change

There was no way to build the doc automatically since the reorganization between the website and the main repo.

It would be nice to add a test of this target in the CI, but I'm not familiar enough with mathcomp's CI setup to do it myself.

@ybertot this should help you with the release process

##### Things done/to do

~- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`~
~- [ ] added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by gares** [comment]
Pending PR: https://github.com/maximedenes/math-comp/pull/2

**Comment by maximedenes** [comment]
I'll rebase to make the history simpler.

**Comment by maximedenes** [comment]
done

**Comment by CohenCyril** [comment]
@ybertot can you review this PR since you are going to use it?

**Comment by CohenCyril** [comment]
PS: I guess the only review that we need would be a successful generation of the doc...

**Comment by gares** [comment]
Yves told me he did try locally.
At some point we should decide to run this in CI, or at least some parts of it, so that it down not bitrot.

**Comment by ybertot** [comment]
I did the review, checked it works with several versions of Coq (8.9, 8.10, and master), and proposed corrections to @mdenes, integrated above.  I am now checking the aspect of the produced documentation.

I vote against a CI test for the makefile entry to produce the documentation, because it will duplicate math-comp compilation and still not provide the actual verification that the produced files are correct.

**Comment by CohenCyril** [comment]
@ybertot did you check the end result?

**Comment by CohenCyril** [comment]
(PS: if so, please approve the PR.)

**Comment by ybertot** [comment]
There is some strange results with new "active" links for some symbols which actually do not point correctly where they should.  I try to understand where they come from (our own stuff or coqdoc).

**Comment by CohenCyril** [comment]
@ybertot great! For further reference, here is the issue you posted https://github.com/coq/coq/issues/11194

**Comment by pi8027** [comment]
`make clean` fails if the doc has not been generated.
```
$ make clean
CLEAN
CLEAN *.aux *.timing
CLEAN
CLEAN *.aux *.timing
rm -r _build_doc/
rm: cannot remove '_build_doc/': No such file or directory
make: *** [Makefile.common:149: doc-clean] Error 1
```

**Pull request merged**
