### PR TITLE
Add number notation for rat

### PR DESCRIPTION
**Pull request by proux01**
##### Motivation for this change

During last meeting https://github.com/math-comp/math-comp/wiki/Minutes-December-1-2021
addition of a `Number Notation` for `rat` was discussed and I promised a draft PR, so here it is,
at least for rat (number notation cannot be defined for arbitrary rings).

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [x] added corresponding documentation in the headers
- [x] added output tests in `test_suite`
- [x] merge #842 

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by CohenCyril** [comment]
That's awesome! Slightly off topic:
- I'd like the same for `int` in another PR
- Could we have the same for an arbitrary ring.

**Comment by proux01** [comment]
> * I'd like the same for `int` in another PR

Sure, that should be an easier PR

> * Could we have the same for an arbitrary ring.

Unfortunately not, Coq requires the parsed type to be an inductive or at least a constant (so not a section variable).
I could probably rather easily extend Coq to have `<number>` be parsed (and printed back) just as `<number>%:R` but I don't know if it's worth it (the `GRing.natmul` wouldn't be computed in any case (if only because we wouldn't know how to print back the result)).

**Comment by proux01** [comment]
Never mind, I just found a hack to do it without modifying Coq itself: #841

**Comment by proux01** [comment]
> * I'd like the same for `int` in another PR

Here it is: #842

**Pull request merged**
