### PR TITLE
Adding missing mxalgebra lemmas

### PR DESCRIPTION
**Pull request by CohenCyril**
##### Motivation for this change

Missing useful trivial tools in mxalgebra.
Part of #207

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- ~added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by affeldt-aist** [comment]
This reminds me of this issue reported to real-closed: https://github.com/math-comp/real-closed/issues/1

**Comment by CohenCyril** [comment]
> This reminds me of this issue reported to real-closed: [math-comp/real-closed#1](https://github.com/math-comp/real-closed/issues/1)

Indeed, cf #577

**Review by thery — APPROVED** [review]
seems ok

**Comment by thery** [comment]
@CohenCyril  I ve meged this pull request, I was wondering if the CHANGELOG should be 
should not collect the changes per files rather than being a list of changes.

**Comment by CohenCyril** [comment]
Due to the new policy on changelogs, (cf minutes of the last meeting) what you say is discouraged. The editing process tou described can be done at release time.

**Comment by thery** [comment]
@CohenCyril  hope it will be done otherwise the CHANGELOG is unreadable

**Comment by CohenCyril** [comment]
> @CohenCyril hope it will be done otherwise the CHANGELOG is unreadable

Sure, I will add it to the HOWTO release.

**Pull request merged**
