### PR TITLE
Remove `_ : Type` from packed classes

### PR DESCRIPTION
**Pull request by anton-trunov**
This PR's purpose is to discuss if it is time to make this change and get some feedback. I did things rather mechanically here, so there might be some room for further improvements.

This increases performance 10% - 15% for Coq v8.6.1 - v8.9.dev.
Tested on a Debain-based 16-core build server and a Macbook Pro laptop with 2,3 GHz Intel Core i5.
It seems Coq at some point fixed the problem `_ : Type` was supposed to solve.

#### Table 1. Debian build server (16 virtual cores), make -j8, real time

|                                        | Compilation time, old (967088a6f87) | Compilation time, new | Speedup |
| -------------------------------------- | ----------------------------------- | --------------------- | ------- |
| Coq 8.6.1                              | 10min 33s                           | 9min 10s              | 15%     |
| Coq 8.7.2                              | 10min 12s                           | 8min 50s              | 15%     |
| Coq 8.8.2                              | 9min 39s                            | 8min 32s              | 13%     |
| Coq 8.9.dev (coq commit 05d827c800544) | 9min 12s                            | 8min 16s              | 11%     |
| Coq 8.10+alpha (coq commit 82eacb323837ac | 6min 33s | 6min 24s | 2.3% |

#### Table 2. Debian build server (16 virtual cores), non-parallel make, real time, Coq 8.8.2

|           | old   | new   | speedup |
| --------- | ----- | ----- | ------- |
| ssreflect | 39s   | 39s   |      0% |
| fingroup  | 54s   | 52s   |    3.8% |
| algebra   | 175s  | 161s  |    8.7% |
| solvable  | 186s  | 181s  |    2.8% |
| field     | 445s  | 357s  |   24.6% |
| character | 245s  | 230s  |    6.5% |
| Total:    | 1144s | 1020s |     12% |

#### Table 3. Debian build server (16 virtual cores), non-parallel make, real time, Coq 8.10+alpha (82eacb323837acc73c2a5bf6b22a7169bbb61e6d)

|           | old   | new   | speedup |
| --------- | ----- | ----- | ------- |
| ssreflect | 37s  | 38s  |   -2.6% |
| fingroup  | 49s  | 50s  |     -2% |
| algebra   | 143s | 140s |    2.1% |
| solvable  | 173s | 170s |    1.8% |
| field     | 209s | 190s |     10% |
| character | 220s | 205s |    7.3% |
| Total:    | 831s | 793s |    4.8% |

### CODE REVIEW

**Comment by anton-trunov** [comment]
@CohenCyril Thank you!

**Comment by thery** [comment]
@anton-trunov is this speed-up for the compilation of the library or for Feit-Thompson?

**Comment by ejgallego** [comment]
I am not sure if this is related, just in case: https://github.com/coq/coq/pull/396

**Comment by gares** [comment]
CC @maximedenes @ppedrot 

IIRC these copies of the first argument (replicated at the end of the record) were there to make the term comparison (of the kernel) fail early (since it goes right-to-left).

Maybe it is never the case that the records touched by this PR needs to be compared as different by the kernel. Is there a way we can check this assertion? Is there a way to keep the parameter still there but ignore it at term comparison time (to be sure this is the place were we gain speed)?

**Comment by anton-trunov** [comment]
> @anton-trunov is this speed-up for the compilation of the library or for Feit-Thompson?

@thery This is speedup for the compilation of all the packages in *this* repository, I didn't test `odd-order` repository.
I also tested the speedups for each individual package, please see the updated initial message.

**Comment by anton-trunov** [comment]
>  I'd be curious to see how this PR fares atop of a recent master containing the aforementioned tweak.

@ppedrot I updated the initial message (see updated table 1 and a new table 3).

Amazing job the Coq devs did! Congrats!

**Comment by gares** [comment]
So this pr is a 10% speedup on top of the 100% speedup given by the coq patch recently merged, on the field component.

I believe that it would be relevant to apply this pr, even if it was gaining nothing on the performance side, since it cleans up the structures. 10% is the cherry on top.

**Comment by CohenCyril** [comment]
So before merging, I would like to
1. have a benchmark on odd-order too, and
2. have a regression test on failure cases for kernel comparison that used to be too slow... @ggonthier, @gares did you keep such examples somewhere?

**Comment by anton-trunov** [comment]
> have a benchmark on odd-order too

It turns out `odd-order` needs a 4-character fix, see [here](https://github.com/anton-trunov/odd-order/commit/10f523ff7d8ed1f52184dd61a56f35410ed18977)) before it can be compiled with this PR.

With that fix, I did a benchmark on the aforementioned laptop with Coq 8.10+alpha (coq/coq@8fb01564fba587142c2471708ff18219f1c64903).
- Old: math-comp/odd-order@10f523ff7d8ed1f52184dd61a56f35410ed18977, mathcomp (967088a6f87405a93ce21971392c58996df8c99f)
`make  906,10s user 13,57s system 99% cpu 15:23,02 total`

- New: math-comp/odd-order@10f523ff7d8ed1f52184dd61a56f35410ed18977, mathcomp (27e3e35be9a6805e126df5b44a9bb5db9a561f5a)
`make  889,57s user 13,55s system 99% cpu 15:06,49 total`

Resulting in 1.86% speedup (probably just noise).

I hope this helps.

**Comment by anton-trunov** [comment]
Rebased to fix a conflict with 03ad994dfee48e1a7b2b7091c45dfdcf4402f826

**Comment by CohenCyril** [comment]
Please also add a ChangeLog entry

**Comment by anton-trunov** [comment]
> Please also add a ChangeLog entry

@CohenCyril Updated. Please let me know if you'd like to expand the entry.

**Pull request merged**
