### PR TITLE
using opam in travis before_install script

### PR DESCRIPTION
**Pull request by CohenCyril**
And triggering a build

### CODE REVIEW

**Comment by ejgallego** [comment]
Note the interaction of '.opam' caching vs installing a coq `.dev` version.
Indeed, to get fully correct builds, you may need to disable caching.

We chose to cache `.opam` as we were really tight on timing and were installing a complete, heavy toolchain there. However, for this kind of setup, `.opam` caching is indeed more of an historical artifact.

**Comment by ejgallego** [comment]
I would also personally test 8.6 vs 8.6.dev, but of course that is a matter of preferences. Also, note that we have two different coq packages in opam, the one in the official repos and the one in coq-dev, @maximedenes , what is going on here?

**Comment by CohenCyril** [comment]
@ejgallego would an opam upgrade be sufficient to trigger the rebuild of coq dev ?

**Comment by ejgallego** [comment]
@CohenCyril that seems like a great thing to try, I am not expert in opam but I think it should work.

**Comment by ejgallego** [comment]
Something to take into account is that caching is far from free in Travis; indeed the download/unpacking + packing/upload time does count for the build. So it could be well the case that we end up losing net time if we download a fully cached Coq version just to rebuild it.

**Comment by CohenCyril** [comment]
Do you have an idea of how much time it takes to use a the cache?
Do you know if it possible to reuse cached data from a Travis build of Coq, so that we decorelate building Coq from building math-comp?

**Comment by ejgallego** [comment]
For a full coq building environment, the cache takes 8 seconds to download an unpack. Then, it takes 30 seconds to reupload it, but this should be surely skipped as the reload is caused by opam adding some unnecessary logging information in `.opam/log`. See: https://travis-ci.org/coq/coq/builds/198948812 for an example.

> Do you know if it possible to reuse cached data from a Travis build of Coq, so that we decorelate building Coq from building math-comp?

Not from the Coq travis run unless we setup something special, I think it is not a good idea. If you want binary packages you'll have to use apt for them.

**Comment by ejgallego** [comment]
From a testing point of view, I think it is a bad idea to decorrelate Coq and Math-comp, IMHO you want to be sure they run well together with the respective tips of the branches, otherwise you delay detection of problems.

More complex CI setups force a rebuild of math-comp whenever Coq changes, however I think we don't have the manpower to do that kind of integration so Coq will take care of its own test and math-comp can use any policy they steem convenient.

**Comment by ejgallego** [comment]
The main reason I am a bit wary of caching coq is that it makes the build process too non-deterministic for my taste; build times may go well when the cache is hit, then a cache invalidation may make things to timeout. And note that the cache is generated at the end of the build.

**Comment by CohenCyril** [comment]
OK, maybe this is not a good idea after all.

**Comment by ejgallego** [comment]
Just to be clear in case I sounded too negative, I don't think that using opam is a bad idea, in fact it seems great to me, however I don't know how to integrate it well with the way Travis learns about dependencies.

**Comment by CohenCyril** [comment]
I think it is technically possible to (automatically) build docker images for each version of Coq we want to test against (8.5.3, 8.6, and latest **compiling** 8.6.dev and dev versions), and reuse these images in our math-comp build, so that each job time is "time to download the appropriate Coq docker image" + "compilation time of mathcomp"... Given there is a docker integration to github, which someone already made work for Coq (cf https://hub.docker.com/r/skippa/coq/builds/)

And if odd-order is still too long, we could put it in an independent repository, store the build of mathcomp in a docker (cf https://sebest.github.io/post/using-travis-ci-to-build-docker-images/) and use this docker to build odd-order.

What do you think @ejgallego ?

**Comment by ejgallego** [comment]
I am not familiar with Docker so I need to read the links first, but it sounds great!

One question thou is how the docker build would interact with the Travis job which is launched at commit time. How do we make the Travis odd_order wait for the math-comp docker image to be ready?

I was also thinking of using the `deploy` capabilities of Travis to indeed build some kind of caching, this should work well for the Coq case without adding too much overhead, (the first job will just upload a `tar.gz` of coq for the rest of ci jobs), however I am not sure mathcomp can really benefit from it.

**Comment by ejgallego** [comment]
For instance, could we teach Coq's Travis build to deploy a Coq docker image at every Coq commit ?

**Comment by CohenCyril** [comment]
yes we can (https://docs.travis-ci.com/user/docker/#Branch-Based-Registry-Pushes)

**Comment by ejgallego** [comment]
That looks great. I could will try to add a docker push to Coq's travis , but it won't happen in February I'm afraid.

**Pull request closed without merging**
