### PR TITLE
Non-distributive lattice

### PR DESCRIPTION
**Pull request by pi8027**
##### Motivation for this change

(For discussion.)

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`
- [ ] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by strub** [comment]
Since I'd like to build on top, I am ok to take the role.

**Comment by amahboubi** [comment]
Cool, thanks @strub ! I am marking you as such.

**Comment by CohenCyril** [comment]
@amahboubi @strub this PR is a draft, I do not think it should have assignee (or that the assignee should be taking actions) before @pi8027 decides it's ready...

**Comment by pi8027** [comment]
I hope I will make this PR ready to merge soon. So it's good to have an assignee. Thank you @strub!

**Comment by pi8027** [comment]
Since I did not find how to change the target branch of an existing PR, I close this PR and open another one to retarget `math-comp:master`.

**Pull request closed without merging**
