### PR TITLE
Fix GitLab CI/CD config

### PR DESCRIPTION
**Pull request by erikmd**
##### Motivation for this change

Cc @gares @CohenCyril 

Follow-up of #1056 (https://github.com/math-comp/math-comp/commit/49aba213e425105087fd0eefb9f576fce088756d) which indirectly required coq ≥ 8.17, see this failure:
* job https://gitlab.inria.fr/math-comp/math-comp/-/jobs/3343340
* from pipeline https://gitlab.inria.fr/math-comp/math-comp/-/pipelines/844235

Hence this PR proposing to drop compatibility of coq 8.16 of mathcomp

Note: I took the opportunity of this PR to re-add CI tests *on pull_requests*, given the new GitLab-Inria infra scales better! 

Cc @math-comp/core, do you approve this PR?

(Anyway we should wait for https://github.com/coq/opam-coq-archive/pull/2668 before merging this one)

##### Things done/to do

- [ ] ~added corresponding entries in `CHANGELOG_UNRELEASED.md`~

- [ ] ~added corresponding documentation in the headers~
- [x] tried to abide by the [contribution guide](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md)

- [ ] TODO propagate the coq-elpi relaxed constraint to extra-dev

##### Compatibility with MathComp 1.X

- [ ] I added the label `TODO: MC-1 port` to make sure someone ports this PR to
      the `mathcomp-1` branch **or** I already opened an issue or PR (please cross reference).

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

### CODE REVIEW

**Comment by erikmd** [comment]
FYI: https://coq.inria.fr is down now, probably till next Wednesday [(cf. Zulip)](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Website.20down.3F/near/384060556)

**Comment by gares** [comment]
I think we should postpone until 8.18 is really out, so to keep the compatibility with 2 coq versions.

**Comment by gares** [comment]
Also, for some reasons, 8.16 does not has "all the bugs" that make MC 2.0 slow, so it is a bit unclear to me if we should really drop it. I don't know if opam's language is sufficiently expressive to impose recent elpi/coq-elpi on 8.17+ only.

**Comment by erikmd** [comment]
@gares OK!

> I don't know if opam's language is sufficiently expressive to impose recent elpi/coq-elpi on 8.17+ only.

Yes that should be feasible, according to https://opam.ocaml.org/doc/Manual.html#Package-Formulas

**Comment by erikmd** [comment]
now that coq.inria.fr is live again, I force-pushed the PR to restore coq.8.16 compatibility.

Also, I removed the `(< "8.19~")` constraint because this look unnecessary (this was already the choice made in opam-coq-archive).

@gares does the final opam look good to you? If yes, I'll propagate the coq-elpi relaxed constraint to `extra-dev`.

Anyway, let's wait for a green CI on GitLab before merging the PR!

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
Ci is still broken on coq dev

**Comment by erikmd** [comment]
> CI is still broken on coq dev

not exactly, as far as I see in https://gitlab.inria.fr/math-comp/math-comp/-/pipelines/845824 :

* the coq.8.18 build failed at coq-elpi.dev build:

https://gitlab.inria.fr/math-comp/math-comp/-/jobs/3354986

```
…
#8 253.7 - File "src/coq_elpi_builtins.ml", line 2926, characters 22-52:
#8 253.7 - 2926 |                (id, ((Notation_ops.constr_some_level,([],[])),Id.Set.empty,Notation_term.NtnTypeConstr)) :: vars in
#8 253.7 -                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#8 253.7 - Error: Unbound value Notation_ops.constr_some_level
#8 253.7 - make[1]: *** [Makefile.coq:752: src/coq_elpi_builtins.cmo] Error 2
#8 253.7 - make: *** [Makefile:50: build-core] Error 2
#8 253.7 [ERROR] The compilation of coq-elpi.dev failed at "make build COQBIN=/home/coq/.opam/4.13.1+flambda/bin/ ELPIDIR=/home/coq/.opam/4.13.1+flambda/lib/elpi OCAMLWARN=".
```

and

* the coq.dev build failed at coq-hierarchy-builder.dev build:

https://gitlab.inria.fr/math-comp/math-comp/-/jobs/3354985

```
#8 370.9 - COQC structures.v
#8 371.5 - File "./structures.v", line 294, characters 0-15:
#8 371.5 - Error:
#8 371.5 - File "/home/coq/.opam/4.13.1+flambda/.opam-switch/build/coq-hierarchy-builder.dev/HB/common/database.elpi", line 231, column 0, character 8401:Cannot spill: unknown arity of gref->modname_short
#8 371.5 - 
#8 371.5 - make[2]: *** [Makefile.coq:838: structures.vo] Error 1
#8 371.5 - make[2]: *** [structures.vo] Deleting file 'structures.glob'
#8 371.5 - make[1]: *** [Makefile.coq:409: all] Error 2
#8 371.5 - make[1]: Leaving directory '/home/coq/.opam/4.13.1+flambda/.opam-switch/build/coq-hierarchy-builder.dev'
#8 371.5 - make: *** [Makefile:97: this-build] Error 2
#8 371.5 [ERROR] The compilation of coq-hierarchy-builder.dev failed at "make build".
```

@gares do you believe an overlay is missing in coq-elpi / coq-hierarchy-builder?

**Comment by erikmd** [comment]
@gares @CohenCyril good news + question:

I restarted the CI, probably after some overlay merging, now this CI-fixup-PR passes with docker-coq.dev:

https://gitlab.inria.fr/math-comp/math-comp/-/jobs/3376711

But not Coq 8.18:

https://gitlab.inria.fr/math-comp/math-comp/-/jobs/3376712

because after installing

```
#8 66.49   - install menhirSdk              dev    [required by menhir]
#8 66.49   - install easy-format            1.3.4  [required by atd]
#8 66.49   - install menhirLib              dev    [required by menhir]
#8 66.49   - install re                     1.11.0 [required by elpi]
#8 66.49   - install camlp-streams          5.0.1  [required by biniou]
#8 66.49   - install menhir                 dev    [required by elpi]
#8 66.49   - install biniou                 1.2.2  [required by atdgen]
#8 66.49   - install atd                    2.12.0 [required by atdgen, atdts]
#8 66.49   - install atdgen-runtime         2.12.0 [required by atdgen]
#8 66.49   - install atdts                  2.12.0 [required by elpi]
#8 66.49   - install atdgen                 2.12.0 [required by elpi]
#8 66.49   - install elpi                   1.17.0 [required by coq-mathcomp-ssreflect]
#8 66.49   - install coq-elpi               dev    [required by coq-hierarchy-builder]
#8 66.49   - install coq-hierarchy-builder  1.5.0  [required by coq-mathcomp-ssreflect]
#8 66.49   - install coq-mathcomp-ssreflect dev*   [required by coq-mathcomp-fingroup]
#8 66.49   - install coq-mathcomp-fingroup  dev*   [required by coq-mathcomp-algebra]
#8 66.49   - install coq-mathcomp-algebra   dev*   [required by coq-mathcomp-solvable]
#8 66.49   - install coq-mathcomp-solvable  dev*   [required by coq-mathcomp-field]
#8 66.49   - install coq-mathcomp-field     dev*   [required by coq-mathcomp-character]
#8 66.49   - install coq-mathcomp-character dev*
```

`coq-elpi.dev` fails with:

```
#8 250.5 # File "src/coq_elpi_builtins.ml", line 2926, characters 22-52:
#8 250.5 # 2926 |                (id, ((Notation_ops.constr_some_level,([],[])),Id.Set.empty,Notation_term.NtnTypeConstr)) :: vars in
#8 250.5 #                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#8 250.5 # Error: Unbound value Notation_ops.constr_some_level
#8 250.5 # make[1]: *** [Makefile.coq:752: src/coq_elpi_builtins.cmo] Error 2
#8 250.5 # make: *** [Makefile:50: build-core] Error 2
```

Ideas to fix/workaround this?

**Comment by proux01** [comment]
@erikmd so the issue is that opam attempts to compile coq-elpi.dev instead of coq-elpi.1.19.0 (c.f. https://github.com/coq/opam/blob/master/extra-dev/packages/coq-elpi/coq-elpi.1.19.0/opam ). I guess the isssue is in https://github.com/coq/opam/blob/master/extra-dev/packages/coq-elpi/coq-elpi.dev/opam and (partly) reverting https://github.com/coq/opam/commit/b4c1d2113b181e8e60a31921b747e71c35dd4fb4 should fix it?

**Comment by erikmd** [comment]
good news, the gitlab CI pipeline is now green, thanks a lot @proux01 !

So I'm going to merge the PR, implying all GitHub PRs will benefit from GitLab CI feedback, using coqbot and gitlab.inria

**Pull request merged**
