### PR TITLE
Resubmitted missing lemma in seq.v

### PR DESCRIPTION
**Pull request by hivert**
See discussion on (https://github.com/math-comp/math-comp/pull/41)

### CODE REVIEW

**Comment by hivert** [comment]
There are some trivial conflicts, but since I Messed things up by trying to resolve them using github interface, I leave it to you to do the merge.

**Comment by CohenCyril** [comment]
I'm on it

**Comment by hivert** [comment]
@CohenCyril: Thanks. One question: I'm ready to resubmit the removed "reshape_index_leq" lemma, however if I do so, you'll have all the other from this pull request too. It doesn't really makes sense to strip the code to what is needed for this single lemma. Should I wait for this pull request being integrated ?

**Comment by hivert** [comment]
One final last comment: now that I have a non trivial contribution to math-comp, I'd be glad to have my name written somewhere in a contributor section ;-) Yes I know: those reseacher/developper with their ego...

**Comment by CohenCyril** [comment]
Good point, until the next release your name is at least in a commit so github automatically lists you as a contributor (https://github.com/math-comp/math-comp/graphs/contributors). Now, when a tarball is made for a release, we have indeed to make sure to have contributor section.

**Pull request merged**
