### PR TITLE
[ci] Extend the test-suite

### LINKED ISSUE #245: Add more libraries to Continuous Integration?
I'd like to see the [math-comp](https://github.com/math-comp) libraries covered by CI for `math-comp/math-comp`, just to be sure no change in this fundamental part breaks e.g. `odd-order`, `analysis`, `finmap` and other libraries.

This issue is related to #159.

### PR DESCRIPTION
**Pull request by erikmd**
This PR should close #245

**Depends on**: #306

See the last commit message for more details.

Cc @CohenCyril @pi8027 @ejgallego

### CODE REVIEW

**Comment by erikmd** [comment]
Rebased on #306

**Comment by CohenCyril** [comment]
Waiting for #306's merge into master to be green...

**Comment by erikmd** [comment]
@CohenCyril
> Waiting for #306's merge into master to be green...

Thanks @CohenCyril ! this is indeed the case:
https://gitlab.com/math-comp/math-comp/pipelines/57204553
and the images have been successfully pushed to https://hub.docker.com/r/mathcomp/mathcomp-dev/tags

**Comment by CohenCyril** [comment]
@erikmd done! thank you for all of this :+1:

**Pull request merged**
