### PR TITLE
rename test-suite -> test_suite to make coq happy

### PR DESCRIPTION
**Pull request by gares**
Should fix issues detected https://github.com/coq/coq/pull/9881

### CODE REVIEW

**Comment by maximedenes** [comment]
How's that the proper fix?! What's wrong with the name "test-suite"?

**Comment by gares** [comment]
What is the real issue?

**Comment by maximedenes** [comment]
> What is the real issue?

Well, that was my question :)

**Comment by maximedenes** [comment]
Is the name `test-suite` forbidden? If not, why this patch?

**Comment by gares** [comment]
It cannot translate to a logical path

**Comment by vbgl** [comment]
Will merging this make Coq CI work again? If so please do merge and investigate the root cause later. Thanks.

**Comment by gares** [comment]
I guess so. IIRC the makefiles generated by Coq makefile ask Coq to resolve paths to logical paths for the installation in user-constribs/. Unfortunately I see no message in the log, but this directory is the only thing that changed.

**Comment by vbgl** [comment]
Coq CI still fails:

> install: cannot stat 'test_suite/hierarchy_test.glob': No such file or directory
Makefile.coq:471: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/builds/coq/coq/_build_ci/mathcomp/mathcomp'
Makefile.ci:69: recipe for target 'ci-coquelicot' failed

**Comment by gares** [comment]
ok, I'll at it closely then

**Comment by gares** [comment]
We found the culprit, @maximedenes is preparing a PR (on Coq)

**Pull request merged**
