### PR TITLE
Adapt w.r.t. coq/coq#16004 after the merge of #813.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
The change clearly introduced a new warning, maybe we need a bit more infrastructure to check this.

**Comment by gares** [comment]
I think the infrastructure is in place since https://github.com/math-comp/math-comp/pull/891 , am I wrong?

**Comment by gares** [comment]
@proux01 was it intended? I thought you wanted to keep the project clean, but _CoqProject is only used by UIs, not by `make` which uses `Make` instead, IIRC

**Comment by proux01** [comment]
No, that's obviously an error from me.

**Comment by proux01** [comment]
Note that
```
-arg -w -arg +deprecated-hint-rewrite-without-locality
```
is wrong (we'll have to wait for MathComp to require Coq >= 8.14 for that).
But we could indeed put
```
-arg -w -arg +deprecated-hint-without-locality
```
in the makefiles.

**Comment by gares** [comment]
yes, this is what I meant.

**Comment by ppedrot** [comment]
Damn, this was not enough. I somehow missed another warning introduced in the meantime. Guess I'll have to open yet another fix PR.

**Pull request merged**
