### PR TITLE
fix(.gitlab-ci.yml): Make it possible to build `mathcomp/mathcomp-dev:coq-8.19`

### PR DESCRIPTION
**Pull request by erikmd**
href: https://github.com/math-comp/docker-mathcomp/pull/32#issuecomment-1896075150

##### Motivation for this change

Fix CI/CD for GitLab CI and Coq 8.19+rc1

Cc @proux01 @pi8027 FYI

##### Things done/to do

This small fixup PR can be merged as soon as the CI is green.

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

### CODE REVIEW

**Comment by proux01** [comment]
Thanks, we indeed forgot to edit that file when doing the release.
Will merge when gitlab CI is green.

**Comment by erikmd** [comment]
> Thanks, we indeed forgot to edit that file when doing the release.

actually, it seems the file was already edited, but partially:

https://github.com/math-comp/math-comp/commit/e1193105b2a5792bfe6f7db45c3bb1840b191f5f#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7

(there are 3 snippets to uncomment)

**Comment by erikmd** [comment]
Side remark:

contrary to math-comp/docker-mathcomp where the GitLab CI check is partial (I mean, the images are linted, but not fully built before the PR lands in master)

the upside of the math-comp/math-comp CI config is that **if we check that the GitLab CI is green before merging the PR**, then we are sure all images for specified versions of Coq will be deployed successfully (modulo network issues, of course)

**Comment by erikmd** [comment]
> Will merge when gitlab CI is green.

Sure (the URL is https://gitlab.inria.fr/math-comp/math-comp/-/pipelines/911863), thank you @proux01

**Pull request merged**
