### PR TITLE
Adding contra lemmas with orders

### PR DESCRIPTION
**Pull request by CohenCyril**
##### Motivation for this change

Adding contraposition lemmas for `leq`, `ltn`, `Order.le` and `Order.lt`.

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- ~added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by CohenCyril** [comment]
@affeldt-aist would you be ok to merge it with #576 and document?

**Comment by CohenCyril** [comment]
LGTM except I'm an author too :laughing:

**Comment by CohenCyril** [comment]
> LGTM except I'm an author too

I meant: I cannot review so the fact it looks good to me is irrelevant.

**Review by pi8027 — APPROVED** [review]

**Comment by CohenCyril** [comment]
(rebased)

**Comment by affeldt-aist** [comment]
I am wondering whether the explanation for the naming of the contra lemmas shouldn't go also into the contributing guide at the root of the repo.

**Comment by CohenCyril** [comment]
> I am wondering whether the explanation for the naming of the contra lemmas shouldn't go also into the contributing guide at the root of the repo.

It would be more appropriate in a general documentation of ssrnat/ssrnum I think. It can be done as a new PR though.

**Review by chdoc — APPROVED** [review]
LGTM. However, given the large number of largely boring lemmas, I wonder whether it would be possible to introduce a `contra:` tactic that automatically picks the right contra lemma, or even constructs it from the shape of the goal. However, I'm not sure how well that would work with the `comparable_*` lemmas.

**Comment by CohenCyril** [comment]
> LGTM. However, given the large number of largely boring lemmas, I wonder whether it would be possible to introduce a `contra:` tactic that automatically picks the right contra lemma, or even constructs it from the shape of the goal. However, I'm not sure how well that would work with the `comparable_*` lemmas.

I see how we could do this using canonical structures / typeclasses ... but for now, let's keep it like this.

**Comment by CohenCyril** [comment]
Please open an issue / feature request with your nice idea  :+1:

**Pull request merged**
