### PR TITLE
Add missing coercion

### PR DESCRIPTION
**Pull request by proux01**
From the mathcomp_extra.v file fo Analysis.

### CODE REVIEW

**Review by affeldt-aist — APPROVED** [review]

**Comment by proux01** [comment]
Thanks for the changelog entry, I indeed forgot it.

**Comment by proux01** [comment]
Thanks @pi8027 this seems to work, so we could:
* merge https://github.com/math-comp/analysis/pull/654
* relaunch CI here
* provided it's green, merge here

**Comment by affeldt-aist** [comment]
The CI seems to indicate that MathComp-Analysis compiles with this commit and KS's trick. Let's merge? @proux01

**Comment by proux01** [comment]
Great

**Pull request merged**
