### PR TITLE
Remove "x : p" notation

### PR DESCRIPTION
**Pull request by proux01**
In prevision of https://github.com/coq/coq/pull/18014

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [x] added corresponding documentation in the headers
- [x] tried to abide by the [contribution guide](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md)

##### Compatibility with MathComp 1.X

- [x] I added the label `TODO: MC-1 port` to make sure someone ports this PR to
      the `mathcomp-1` branch **or** I already opened an issue or PR (please cross reference).

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

### CODE REVIEW

**Comment by CohenCyril** [comment]
I think a better fix would be the addition of one (or two) new grammar entries, dedicated to group presentation.

**Comment by proux01** [comment]
So, I tried hard to find a better solution but this is a pure nightmare:
* ideally one would like a recursive notation `Grp (x, .. , y : p )` which could work, if it weren't for the last case that is missing a `Generator` in the `Cast` around `p`
* so one would like to use something like `Grp (x , .. , y & z : p)` which works for at least two idents (x,..,y is at most one plus z), note that `x` and `y` must be closed binders for the recursive notation to work since they are used as binders in the right hand side of the notation
* so one needs an additional notation `Grp (x : p)` for the case of a single id, and for some reason that just doesn't work, whether `x` is declared ident of (closed) binder.

I already wasted way too much time on this notation that is only used a couple of times in a single file (extremal.v) so except if anyone has a good solution, we should probably go with the current (bad) workaround.

Of course an alternative would be ugly notations like `Grp (x : p)` and `Grp (& x,..., y & z : p)` which seems to work.

**Comment by CohenCyril** [comment]
Looks good to me!!
Thanks @proux01

**Comment by proux01** [comment]
Yes you were right about the custom entry @CohenCyril , that works well.
I'm pretty worried about the Nix CI though: it seems to build nothing an always return a green result (errors in a previous iteration were only catched by the Docker CI), I still don't understand why though.

**Comment by proux01** [comment]
FTR, this PR should fix the CI: https://github.com/coq-community/coq-nix-toolbox/pull/162 Let's wait for it to be merged and relaunch CI here.

**Comment by proux01** [comment]
CI "green" (deriving isn't ported to MC2 yet, I should disable it in another PR).

**Pull request merged**
