### PR TITLE
generalize take_take and add take_takel and take_taker

### PR DESCRIPTION
**Pull request by thery**
##### Motivation for this change

More generic theorem `take_take`

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by CohenCyril** [comment]
Great! But even if the CI does not seem to show a single failure, this change is not backward compatible. I'm a little bit hesitant to approve. It could be make backward compatible at the cost of naming the new (generalized) lemma slightly differently (e.g. `take_take_min`, or just `take_min` swapping the RHS and LHS of the equality).
@thery what do you think?

**Comment by pi8027** [comment]
Related discussion: https://github.com/math-comp/math-comp/pull/381#discussion_r320603902

**Comment by thery** [comment]
@pi8027 oops I've missed that discussion. I know it is a breaking change but don't you think it is more reasonable like this?

**Review by CohenCyril — APPROVED** [review]
Let's rebase and merge

**Pull request merged**
