### PR TITLE
[div] Move dvdn_fact from prime to div.

### PR DESCRIPTION
**Pull request by ejgallego**
Hi,

I was wondering whether it would make sense to merge this lemma by GG.

```` coq
Lemma dvdn_fact m n : 0 < m <= n -> m %| n`!.
````

My request has no other reason than a selfish desire to improve the welcome page at https://x80.org/rhino-coq.

### CODE REVIEW

**Comment by amahboubi** [comment]
Hi Emilio, 

this lemma already exists in [prime.v](https://github.com/math-comp/math-comp/blob/master/mathcomp/ssreflect/prime.v#L593), under the same name (and with the same proof).

But I agree it looks misplaced, so we could indeed move it to div. Any objection?

**Comment by ejgallego** [comment]
Hi Assia,

Ups! Sorry for the noise, I had this on my TODO from mathcomp 1.5 times I guess and forgot to double check. Please close.

Indeed it would make more sense to have it in `div`, the lemma seems to be added in 1.6 so I guess not a lot of users should be impacted by the change. I've updated the PR just in case.

**Comment by amahboubi** [comment]
Many thanks for the PR update!

**Comment by ejgallego** [comment]
Thanks Assia !

**Pull request merged**
