### PR TITLE
Fix ML compilation after Ltac refactoring.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by gares** [comment]
I think the change to Make is wrong, isn't the Makefile adding that line (on some versions of Coq)?

**Comment by ppedrot** [comment]
Oh, you're right. I tend to use `git commit -a` too easily. I'll push a fixup.

**Comment by gares** [comment]
I could not find a better hack, patching Make is ugly, but only 8.6+ wants the mlpack file...

**Comment by ppedrot** [comment]
Couldn't you that using some form of conditional inclusion in the makefile?

**Comment by ejgallego** [comment]
@gares, note that the makefile patching mess things for me in the following way:
- after a make the git checkout won't be clean.
- repeated copies of `ssreflect_plugin.mlpack` get added every time make is run.

**Pull request closed without merging**
