### PR TITLE
Remove the mc_1_9 compat module

### LINKED ISSUE #488: Remove mc_1_9
Remove module `mc_1_9` in `ssrnat.v` for milestone 1.12.

### PR DESCRIPTION
**Pull request by pi8027**
##### Motivation for this change

Closes #488

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- ~[ ] added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by pi8027** [comment]
Do we need a CHANGELOG entry for this?

**Comment by affeldt-aist** [comment]
> Do we need a CHANGELOG entry for this?

It won't hurt so I would say "yes".

**Comment by pi8027** [comment]
OK.

**Review by CohenCyril — APPROVED** [review]
LGTM

**Pull request merged**
