### PR TITLE
[WIP] Archimedean structures on top of num/real domain/field/closedField

### PR DESCRIPTION
**Pull request by Sobernard**
Includes canonical structures for archimedean versions of the ssrnum structures, and the properties that are derived from the archimedean axiom (refactorization of algC/ssrnum, mainly concerning the int and nat subsets)

### CODE REVIEW

**Comment by CohenCyril** [comment]
Can you add TODO boxes ([ ]) and include a ChangeLog entry (or a TODO for it)

**Comment by amahboubi** [comment]
@CohenCyril, @gares I do not understand the output of CI here. Can someone explain?

**Comment by gares** [comment]
Looks like this pr is based on a broken ssrnum, or it introduces a notation that breaks the parser for ssrnum. I don't have time to check the details but the failure is not spurious to me.

**Comment by pi8027** [comment]
@Sobernard @CohenCyril @amahboubi Hello. I found this PR is useful for my study on intervals and QE. If you don't plan to rebase and fix this, may I rebase this on top of #270? (I intend to do it in November or December.)

**Comment by amahboubi** [comment]
Hi @pi8027 . I personally have no plans to fix / modify this. I guess @Sobernard, the original author, is the one to contact. @Sobernard , if we do not hear from you before the end of October, we will take ownership of the PR. But feel free to tell us so if you want to work on it, and need more time!

**Comment by pi8027** [comment]
Just not to forget to rework this PR, I assign myself.

**Comment by pi8027** [comment]
Now I'm reworking this PR. I guess one of `NumArchiClosedField` and `RealClosedArchiField` should be renamed (`ArchiClosed` or `ClosedArchi`?). Also putting `Archi` somewhere between `RealClosedField` is a bit unfortunate since it does not allow us to abbreviate it as `rcf`.

**Comment by CohenCyril** [comment]
I guess it should be `ArchiNumClosedField` and `ArchiRealClosedField` (the abbrev could be `archiRcf`)

**Comment by CohenCyril** [comment]
Although these are two "distinct notion of closeness" they are very related, indeed `is_real_closed R <-> is_algebraically_closed R[i]` (the left to right direction is proven in `complex.v` and the other direction must be trivial). And conversely I believe `is_algebraically_closed C <-> is_real_closed {x : C | x \is a Num.real}` should be straightforward if one shows `C` and `{x : C | x \is a Num.real}[i]` is a `numField` isomorphism...

**Pull request closed without merging**
