### PR TITLE
Remove old compatibility code for Coq < 8.13

### PR DESCRIPTION
**Pull request by proux01**
This code is now useless since we require Coq >= 8.13.

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)

##### Overlay (to be merged before the PR)
* https://github.com/math-comp/analysis/pull/666

### CODE REVIEW

**Comment by proux01** [comment]
Any assignee? (this should be a rather easy one)

**Comment by affeldt-aist** [comment]
I skimmed through the changelog and found no mistake.

**Comment by proux01** [comment]
@affeldt-aist good catch, some lemmas indeed have slightly different implicit arguments, I warned on that in the changelog and made a (backward compatible) overlay for analysis: https://github.com/math-comp/analysis/pull/666

**Comment by proux01** [comment]
Thanks @affeldt-aist so analysis is now fine and CI is "green"

**Review by affeldt-aist — APPROVED** [review]

**Pull request merged**
