### PR TITLE
fixes #967 (duplicate ssrfun.v/eqtype.v)

### LINKED ISSUE #967: duplicate of Coq's ssrfun code
https://github.com/math-comp/math-comp/blob/8b7c9270d284bf476bf9e52a0026e9435a983041/mathcomp/ssreflect/eqtype.v#L709-L727

duplicate of
https://github.com/coq/coq/blob/master/theories/ssr/ssrfun.v#L570-L588

### PR DESCRIPTION
**Pull request by affeldt-aist**
##### Motivation for this change

fixes #967

##### Things done/to do

~~- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)~~
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by affeldt-aist** [comment]
This should be fixed in Coq : https://github.com/coq/coq/pull/17249

**Comment by affeldt-aist** [comment]
Related problem: PR #968

**Comment by affeldt-aist** [comment]
TODO: close this if PR #968 and https://github.com/coq/coq/pull/17249 go through

**Comment by proux01** [comment]
@affeldt-aist even if https://github.com/coq/coq/pull/17249 goes through, you should add the switched notations in `mathcomp/ssreflect/ssrfun.v` below a `(* 8.18 additions *)` comment (that will be removed once mathcomp requires COq >= 8.18). Otheriwse, merging this as is will reintroduce the printing bug for sval.

**Comment by affeldt-aist** [comment]
@proux01 Thank you!

**Comment by proux01** [comment]
According to CI, Coquelicot requires a patch, I sent a fix to Guillaume.

**Comment by proux01** [comment]
Fixed, let's merge

**Pull request merged**
