### PR TITLE
Cancel lemmas implicit

### PR DESCRIPTION
**Pull request by ggonthier**
Make trailing implicit parameters of cancel f g and {in D, cancel f g} lemmas maximal, so that these lemmas are easier to pass to canLR, canLR_in, and similar.

### CODE REVIEW

**Comment by anton-trunov** [comment]
Would it make sense to add an entry to ChangeLog in this PR to fix #258? Or should I open a new one?
I guess the proposed entry 
```
	* Documented argument names for functions and lemmas. Renamed some
	  of the arguments for consistency reasons. Changed implicit status from
	  non-maximal to maximal for a number of arguments.
```
should be changed anyways.

**Comment by ggonthier** [comment]
@anton-trunov , yes, one entry should suffice to cover both PRs, and it should be a little more precise than the on proposed. I'm working on extending slightly the PR to cover uses of the lemmas  as suggested by @CohenCyril, and also to include partial function cancellation lemmas.

**Comment by ggonthier** [comment]
Added usage, partial function cancel (`pcancel` / `ocancel`), and some residual `injective` / `cancel` lemmas.
Rebased, documented (in Changes, also covering #255), and squashed.

**Comment by gares** [comment]
odd order is now part of Coq's CI and runs on each PR, so breaking it is not nice.

What I do for elpi is to have Coq CI track a branch other than master that I synchronize with master when I'm sure. See https://github.com/coq/coq/blob/master/dev/ci/README-users.md#recommended-branching-policy for example.

We could also improve CI here, so that we test odd-order too before merging.

**Comment by ggonthier** [comment]
I've corrected the issue in odd-order,  and also submitted #264 to correct related issues in `mxrepresentation.v`.

**Pull request merged**
