### PR TITLE
Remove 1.11 and 1.12 deprecations

### LINKED ISSUE #590: remove `big_uncond`
**For mathcomp 1.14.0**, remove `big_uncond` (i.e. the deprecation warning set for 1.13.0 in #589, cf #492)

Also remove other 1.13.0 deprecations

### PR DESCRIPTION
**Pull request by affeldt-aist**
##### Motivation for this change

fixes #590 

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

##### Overlays:
* https://github.com/math-comp/finmap/pull/97
* https://github.com/coq-community/fourcolor/pull/46

### CODE REVIEW

**Comment by affeldt-aist** [comment]
> It feels strange to me to only remove one thing out of 22 in the 1.13 list and keep the remaining?

You're right. Let's do that as part of this PR. I'll do that ASAP.

**Comment by affeldt-aist** [comment]
> > It feels strange to me to only remove one thing out of 22 in the 1.13 list and keep the remaining?
> 
> You're right. Let's do that as part of this PR. I'll do that ASAP.

Are we really supposed to remove the deprecated items marked as 1.13.0? (I understand that `big_uncond` is one of them.)

**Comment by proux01** [comment]
@affeldt-aist I agree to remove only 1.11 and 1.12 deprecations

This is ready, CI "green" (docker CI failures are due to the lack of overlay for finmap, but this works in Nix CI),
the overlay https://github.com/math-comp/finmap/pull/97 should be merged first before merging the current PR (minus the overlay commit)

**Comment by proux01** [comment]
Coq dev in Nix CI is broken since https://github.com/coq/coq/pull/15560 but Docker CI is ok,
so I think this can be merged.

**Pull request merged**
