### PR TITLE
remove addnS's dependence on plus_n_Sm

### PR DESCRIPTION
**Pull request by soraros**

### CODE REVIEW

**Comment by ggonthier** [comment]
Good catch! The `finmap-dev` failure is actually a `finmap` bug, now corrected by math-comp/finmap#38; unfortunately GitLab doesn't let you rerun checks manually.
Ideally, we also should try to remove the `plus_n_Sm` hint, to see if it's being accidentally used elsewhere.

**Comment by soraros** [comment]
The output of `Print HintDb core.`
```
Non-discriminated database
Unfoldable variable definitions: none
Unfoldable constant definitions: none
Cut: emp
For any goal ->   
For CompSpec ->   unfold CompSpec(level 4, id 0) 
For CompSpecT ->   unfold CompSpecT(level 4, id 0) 
For ge ->   unfold ge(level 4, id 0) 
For gt ->   unfold gt(level 4, id 0) 
For lt ->   unfold lt(level 4, id 0) 
For not ->   simple apply n_Sn(level 0, pattern ?META105 <> S ?META105, id 0)
             simple apply O_S(level 0, pattern 0 <> S ?META103, id 0)
             simple apply not_eq_S(level 1, pattern S ?META97 <> S ?META98, id 0)
             simple apply not_eq_sym ; trivial(level 1, pattern 
             ?META51 <> ?META50 :> ?META49, id 0) unfold not(level 4, id 0) 
For notT ->   simple apply not_identity_sym ; trivial(level 1, pattern 
              notT (identity ?META87 ?META86), id 0) 
For BoolSpec ->   simple apply BoolSpecF(level 1, pattern 
                  BoolSpec ?META48 ?META49 false, id 0)
                  simple apply BoolSpecT(level 1, pattern 
                  BoolSpec ?META45 ?META46 true, id 0) 
For CompareSpec ->   simple apply CompGt(level 1, pattern 
                     CompareSpec ?META85 ?META86 ?META87 Gt, id 0)
                     simple apply CompLt(level 1, pattern 
                     CompareSpec ?META81 ?META82 ?META83 Lt, id 0)
                     simple apply CompEq(level 1, pattern 
                     CompareSpec ?META77 ?META78 ?META79 Eq, id 0) 
For CompareSpecT ->   simple apply CompGtT(level 1, pattern 
                      CompareSpecT ?META109 ?META110 ?META111 Gt, id 0)
                      simple apply CompLtT(level 1, pattern 
                      CompareSpecT ?META105 ?META106 ?META107 Lt, id 0)
                      simple apply CompEqT(level 1, pattern 
                      CompareSpecT ?META101 ?META102 ?META103 Eq, id 0) 
For True ->   exact I(level 0, pattern True, id 0) 
For and ->   simple apply conj(level 2, pattern ?META1 /\ ?META2, id 0) 
For eq ->   simple apply mult_n_Sm(level 0, pattern ?META147 * ?META148 + ?META147 =
                                                    ?META147 * S ?META148, id 0)
            simple apply mult_n_O(level 0, pattern 0 = ?META145 * 0, id 0)
            simple apply plus_n_Sm(level 0, pattern S (?META129 + ?META130) =
                                                    ?META129 + S ?META130, id 0)
            simple apply @eq_refl(level 0, pattern ?META125 = ?META125 :> ?META124, id 0)
            simple apply plus_n_O(level 0, pattern ?META123 = ?META123 + 0, id 0)
            simple apply eq_add_S ; trivial(level 1, pattern 
            ?META91 = ?META92, id 0)
            simple apply f_equal_nat(level 1, pattern ?META82 ?META83 =
                                                      ?META82 ?META84 :> 
                                                      ?META81, id 0)
            simple apply eq_sym ; trivial(level 1, pattern 
            ?META47 = ?META46 :> ?META45, id 0)
            simple apply f_equal2_mult(level 2, pattern ?META133 * ?META135 =
                                                        ?META134 * ?META136, id 0)
            simple apply f_equal2_nat(level 2, pattern ?META108 ?META109 ?META111 =
                                                       ?META108 ?META110 ?META112 :>
                                                       ?META107, id 0) 
For ex ->   simple eapply ex_intro(level 2, pattern ex ?META26, id 0) 
For ex2 ->   simple eapply ex_intro2(level 3, pattern exists2 x : 
                                                      ?META29, 
                                                      ?META30 x & ?META31 x, id 0) 
For identity ->   simple apply identity_refl(level 0, pattern 
                  identity ?META126 ?META126, id 0)
                  simple apply identity_sym ; trivial(level 1, pattern 
                  identity ?META83 ?META82, id 0) 
For inhabited ->   simple apply inhabits(level 1, pattern inhabited ?META61, id 0) 
For le ->   simple apply le_n(level 0, pattern ?META151 <= ?META151, id 0)
            simple apply le_S(level 1, pattern ?META152 <= S ?META153, id 0) 
For or ->   simple apply or_intror(level 1, pattern ?META8 \/ ?META9, id 0)
            simple apply or_introl(level 1, pattern ?META5 \/ ?META6, id 0) 
For prod ->   simple apply @pair(level 2, pattern (?META57 * ?META58)%type, id 0) 
For sig ->   simple eapply exist(level 2, pattern {x : ?META105 | ?META106 x}, id 0) 
For sig2 ->   simple eapply exist2(level 3, pattern {x : ?META109 | 
                                                    ?META110 x & 
                                                    ?META111 x}, id 0) 
For sigT ->   simple eapply existT(level 2, pattern {x : ?META115 & ?META116 x}, id 0) 
For sigT2 ->   simple eapply existT2(level 3, pattern {x : 
                                                      ?META119 & 
                                                      ?META120 x & 
                                                      ?META121 x}, id 0) 
For sum ->   simple apply @inr(level 1, pattern (?META64 + ?META65)%type, id 0)
             simple apply @inl(level 1, pattern (?META61 + ?META62)%type, id 0) 
For sumbool ->   simple apply @right(level 1, pattern {?META84} + {?META85}, id 0)
                 simple apply @left(level 1, pattern {?META81} + {?META82}, id 0) 
For sumor ->   simple apply @inright(level 1, pattern ?META90 + {?META91}, id 0)
               simple apply @inleft(level 1, pattern ?META87 + {?META88}, id 0) 
```

**Comment by ggonthier** [comment]
@soraros, thanks for taking a closer look; the only hints we should be concerned with are `plus_n_0`, `plus_n_Sm`, `mult_n_0` and `mult_n_Sm`. The others are irrelevant to `by ...` because they are either at level > 0 and thus not used by `trivial`, and/or otherwise covered by the default `done` (for example, via `discriminate` or `split`).
  We should certainly get rid of them within `ssrnat.v`, and it would be useful to check whether we can do so for the rest of MathComp, or if we should add some of `addn0`, `addnS`, `muln0` and `mulnS` to replace them, perhaps as `Extern` hints that warn against their use.

**Comment by soraros** [comment]
@ggonthier, thank you for clarifying. However, I'm quite new to ssr, and coq so I'm afraid I'm incompetent to do any of the things you suggested properly.
So, shall I close this PR?

**Comment by ggonthier** [comment]
@soraros, I'm fine with you just completing this PR by removing all other uses of `Arith` lemmas from `ssrnat`. By "check" I just meant trying to see how much of rest of the library compiles with your `Remove Hints` command, but we can leave that experiment for another PR.

**Comment by soraros** [comment]
Sorry, I accidentally close the PR (changed the branch name and the pr got closed).
Anyway, I created a new one at [#344](https://github.com/math-comp/math-comp/pull/344).

**Pull request closed without merging**
