### PR TITLE
Fintype doc

### PR DESCRIPTION
**Pull request by proux01**
Make fintype doc more accessible to new users of 'I_n (see https://github.com/coq/coq/pull/18032#issuecomment-1751725239 )

### CODE REVIEW

**Review by ybertot — COMMENTED** [review]
This is mostly reordering the information that was already present.  I don't see makes the doc to new users of 'I_n

I am not sure that the sentence "Finiteness could be stated more simply by bounding the range of the pickle function" is really simpler for new users of 'I_n

**Comment by proux01** [comment]
> This is mostly reordering the information that was already present. I don't see makes the doc to new users of 'I_n

The goal is just to save them reading elaborate things about fintypes before the doc of `'I_n`. No miracles but that should still be an improvement.

> I am not sure that the sentence "Finiteness could be stated more simply by bounding the range of the pickle function" is really simpler for new users of 'I_n

Indeed, that sentence is non trivial and not very useful for a new user, hence moving it towards the end rather than keeping it upfront (I haven't modified it though).

**Comment by CohenCyril** [comment]
> hence moving it towards the end rather than keeping it upfront (I haven't modified it though).

Since it is an implementation detail, maybe it should be moved near the finiteness mixin instead?

**Review by affeldt-aist — APPROVED** [review]
This definitely simplifies the header.

**Pull request merged**
