### PR TITLE
Avoid reusing the name of `take_take`

### PR DESCRIPTION
**Pull request by CohenCyril**
##### Motivation for this change

Fixing [a problem declared on Zulip](https://coq.zulipchat.com/#narrow/stream/237665-math-comp-devs/topic/breaking.20change.20of.20take_take/near/304290639) introduced by #909

CC @thery @palmskog

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- ~added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by CohenCyril** [comment]
Actually `take_min` might be a better choice than `take_take`... what do you think @thery?
Should we add commit 10f5a1cbb5f77020bfa3d0b3afff8387828c7116 or not?

**Comment by thery** [comment]
do you want to deprecate take_take and only lieave take_taker and take_takel?

**Comment by thery** [comment]
ok this is what you did :+1:

**Comment by CohenCyril** [comment]
> do you want to deprecate take_take and only lieave take_taker and take_takel?

Actually I was considering deprecating nothing and keeping `take_min`, `take_take` (as it was in 1.15) and `take_taker`, since actually `take_min` seems at least as natural to me than the "new" `take_take` (from the current `master` branch)...
What do you think @thery?

**Comment by thery** [comment]
I find a bit strange to have `take_taker` and not `take_takel` but  there are other places in the library where it is like this, for example  `comp_polyXr`

**Comment by thery** [comment]
maybe it makes sense to have `take_takel` since there is no reason to priviledge `i<=j` to `j<=i`

**Review by thery — COMMENTED** [review]
Fine with me

**Pull request merged**
