### PR TITLE
`comm(Cmx|_mxC)` -> `comm(_scalar_mx|_mx_scalar)`

### LINKED ISSUE #631: Scalar matrices are not constant matrices and should not use suffix `C`
https://github.com/math-comp/math-comp/blob/26a35314966a28880888eefe62ef053f0b9f038f/mathcomp/algebra/matrix.v#L2892-L2896

### PR DESCRIPTION
**Pull request by CohenCyril**
##### Motivation for this change

Fixes #631 
##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- ~added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by chdoc** [comment]
@CohenCyril Do I understand correctly that this is merely renaming a bunch of lemmas that are not contained in any previous release?

@ybertot @thery , could you please have a look (review) and confirm that the new names are well-chosen?

**Review by thery — APPROVED** [review]

**Comment by ybertot** [comment]
I have no confidence in judging naming policies.  I prefer to pass on this one.

**Comment by CohenCyril** [comment]
> @CohenCyril Do I understand correctly that this is merely renaming a bunch of lemmas that are not contained in any previous release?

yes that's correct!

**Comment by chdoc** [comment]
@thery can you merge this?

**Comment by thery** [comment]
@chdoc yep

**Comment by CohenCyril** [comment]
@thery?

**Comment by chdoc** [comment]
@thery please merge, I cannot.

**Pull request merged**
