### PR TITLE
Redirects to math-comp.github.io

### PR DESCRIPTION
**Pull request by CohenCyril**
### Motivation for this change

Redirects http://math-comp.github.io/math-comp/ to http://math-comp.github.io as asked by @amahboubi in https://github.com/math-comp/math-comp/issues/361#issuecomment-507648368.

Merge only after solving issue https://github.com/math-comp/math-comp/issues/361

##### Things done/to do

- ~~added corresponding entries in `CHANGELOG_UNRELEASED.md`~~
- ~~added corresponding documentation in the headers~~
- [ ]  issue https://github.com/math-comp/math-comp/issues/361 solved

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by maximedenes** [comment]
Please remove other pages than `index.html`, otherwise outdated information will still be visible.

Alternatively, you can also make a redirection for each page, but that's more work.

**Comment by maximedenes** [comment]
The failure looks spurious, but I don't have the rights to restart the job, it seems. Who can I ask?

**Comment by maximedenes** [comment]
It seems you have enough permissions to add me to the gitlab mathcomp organization, @CohenCyril.

**Comment by amahboubi** [comment]
@maximedenes do you really mean gitlab? BTW you are member of math-comp core, what permission do you need exactly?

**Comment by amahboubi** [comment]
Ah ok, sorry for the noise. So I let you handle this.

**Comment by CohenCyril** [comment]
> It would be better to add all mathcomp developers, btw, restarting builds is very useful.

not all mathcomp dev have a gitlab account :-/

**Comment by amahboubi** [comment]
> not all mathcomp dev have a gitlab account :-/

I think we were never prompted to create one. Should we? Is it a gitlab or gitlab.inria account which is needed?

**Comment by maximedenes** [comment]
> I think we were never prompted to create one. Should we? Is it a gitlab or gitlab.inria account which is needed?

It's a gitlab.com account. I think it is likely to be useful for all developers, at least of you want to be able to launch / restart CI builds.

**Comment by amahboubi** [comment]
Done for me. @CohenCyril can you grant me access ?

**Comment by amahboubi** [comment]
Ping @CohenCyril . Can you add me to the gitlab organization?

**Comment by CohenCyril** [comment]
> Ping @CohenCyril . Can you add me to the gitlab organization?

done

**Comment by CohenCyril** [comment]
@maximedenes is there a reason not to merge this anymore?

**Comment by maximedenes** [comment]
> is there a reason not to merge this anymore?

Not that I know of :)

**Pull request merged**
