### PR TITLE
Remove support for Travis CI (mathcomp switched to Gitlab CI)

### PR DESCRIPTION
**Pull request by anton-trunov**
##### Motivation for this change

When working on PR #351 I've received some emails from Travis CI saying that Coq 8.6 job was failing. This is not surprising because Coq 8.6 does not come with integrated SSReflect.

##### Things done/to do

This PR drops support for Travis CI to avoid those failures since Mathcomp already switched to Gitlab CI with coqbot.

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Comment by CohenCyril** [comment]
Dear @anton-trunov the failure in #351 was legitimate, and we do not use travis anymore (but gitlab-ci synced with coqbot), so you might as well remove `.travis.yml` altogether.

**Comment by anton-trunov** [comment]
> Dear @anton-trunov the failure in #351 was legitimate

Dear @CohenCyril, I agree that the last one was legitimate due to finmap relying on `sumbool` type for `eqVneq`, I meant some failures before that.

> we do not use travis anymore (but gitlab-ci synced with coqbot), so you might as well remove .travis.yml altogether.

I wasn't aware of that, will remove it.

**Comment by anton-trunov** [comment]
Yesterday I got a bunch of emails from Travis, saying that the build was failing for Coq 8.6. It would feel nice not to get those :)

**Comment by CohenCyril** [comment]
> Yesterday I got a bunch of emails from Travis, saying that the build was failing for Coq 8.6. It would feel nice not to get those :)

I think it is your personal travis running. I agree let's get rid of it.

**Comment by anton-trunov** [comment]
Oh, I see now. Thanks.

**Pull request merged**
