### PR TITLE
typo in documentation of allpairs_dep

### PR DESCRIPTION
**Pull request by ybertot**
##### Motivation for this change

 simple correction of the documentation

##### Things done/to do

~- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)~
~- [ ] added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

### CODE REVIEW

**Review by CohenCyril — APPROVED** [review]
Thanks :+1:

**Comment by CohenCyril** [comment]
@ybertot did you submit this PR just to own the #666???

**Comment by ybertot** [comment]
Well spotted, but ... no
I wish I had your talent to see funny things in daily life and make witty remarks about them.

**Comment by CohenCyril** [comment]
Btw I just noticed the fix is wrong 😹😹😹 it should be `x`

**Pull request merged**
