### PR TITLE
[opam] fix package metadata

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by CohenCyril** [comment]
@gares we should add `--ignore-constraints-on` in the CI file for coq-dev.

**Comment by gares** [comment]
yup, you are right

**Comment by CohenCyril** [comment]
@gares can you revive this PR? (Rebase + required fix for coq-dev?)

**Comment by gares** [comment]
I've rebased it and it turned out to be a no-op (in some way the changes are already in master).
Hence github thinks the PR was merged, since it's tip is contained in master (it is actually master).
well...

**Pull request closed without merging**
