### PR TITLE
Inverse of products + related lemmas

### PR DESCRIPTION
**Pull request by hivert**
##### Add lemmas expressing the inverse of a product

This PR add a few missing lemma about products (commutative or not) in unitary ring.
The most important one is
```
Lemma prodrV (I : eqType) (r : seq I) (P : pred I) (E : I -> R) :
  (forall i, P i -> E i \is a GRing.unit) ->
  \prod_(i <- r | P i) (E i)^-1 = (\prod_(i <- r | P i) E i)^-1.
```

##### Minimal TODO list

- [x ] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [ ] ~added corresponding documentation in the headers~
- [x ] tried to abide by the [contribution guide](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md)
- [ ] this PR contains an optimum number of meaningful commits

See [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) for details.

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs).

### CODE REVIEW

**Comment by hivert** [comment]
I guess the failure in CoqEal is unrelated. If so it is ready for review. The main point to be discuss is the naming of the lemmas, in particular `rev_prodrV` which is the non-commutative analogue of `prodrV`.

**Review by CohenCyril — APPROVED** [review]
LGTM, I would rename `rev_prod*` to `prod*_converse` though

**Comment by hivert** [comment]
> LGTM, I would rename `rev_prod*` to `prod*_converse` though

It was my first idea, but I changed it after I saw the lemma:
```
Lemma rev_unitrP (x y : R^c) : y * x = 1 /\ x * y = 1 -> x \is a unit.
Proof. by case=> [yx1 xy1]; apply/unitrP; exists y. Qed.
```
Let me know if you still want the change or not.

**Comment by hivert** [comment]
I can't reproduce the failure which seem related to being tested with coq-master (which I don't have)... Not sure what to do here.

**Comment by hivert** [comment]
I don't know if someone else need to review Cyril's changes and if I would be considered as a possible reviewer.  Anyway, if so, I'm positively reviewing Cyril's change !

**Comment by proux01** [comment]
We don't have any strict rule. Anyone can definitely comment on anything. I trust Cyril to ask for an additional review if he feels he authored too much of a PR to merge it himself.

**Pull request merged**
